### ISSUE TITLE
found bug in code line no 7

### ISSUE THREAD

**Issue by sagarsunitha** [sagarsunitha/AZ400#1]
Hi Team,

I found a bug in code line **7. This need to check.

**Comment by bipeensinha** [comment]
Hi TL , I am woerking on this issues . will keep ypu posted

**Comment by ragha9090** [comment]
Raghav Changes working on it

**Comment by bipeensinha** [comment]
![a](https://user-images.githubusercontent.com/49720823/107187247-b6dc2f80-6a0b-11eb-8ab5-2224e4e4f5d8.png)
I found and fix it

**Comment by ragha9090** [comment]
Thank you
![DSC_2901](https://user-images.githubusercontent.com/78528333/107187522-0d327980-69de-11eb-9fe0-336ee91b9e11.jpeg)

**Comment by sagarsunitha** [comment]
Hi Please change it
![spring-flowers-blue-crocuses-drops-water-backgro-background-tracks-rain-113784722](https://user-images.githubusercontent.com/20344203/107187426-e2482580-69dd-11eb-9364-de593f50dbf8.jpg)

**Comment by sagarsunitha** [comment]
code is fixed and we can close this issue now.
